Partial, learn-as-we-go commit with tools and other useful things.

diff --git a/dzap b/dzap
--- a/dzap
+++ b/dzap
@@ -19,11 +19,15 @@ function assertUserNeedsHelp {
 
 
 function assertContainerIsRunning {
-   local container="$1" 
+    local container="$1" 
 
-   docker ps | awk -v "container=$container" 'BEGIN { status = 2; } $NF == container && NR > 1 { status = 0; exit(status); } END { exit(status); }'
+    docker ps | awk -v "container=$container" 'BEGIN { status = 2; } $NF == container && NR > 1 { status = 0; exit(status); } END { exit(status); }'
 
-   [[ "$?" != "0" ]] && die "Container: \"$container\" is not running, even if it's registered; manual removal required" "2"
+    if [[ "$?" != "0" ]]
+    then
+        docker ps | awk 'NR > 1 { if (!found) printf("Containers:\n-----------\n"); print($NF); found = 1; } END { if (found) print(" "); }'
+        die "Container: \"$container\" is not running, even if it's registered; manual removal required" "2"
+    fi
 } # assertContainerIsRunning
 
 
@@ -33,9 +37,7 @@ function assertContainerIsRunning {
 container="$1"
 
 assertArgumentList "$1"
-
 assertUserNeedsHelp "$1"
-
 assertContainerIsRunning "$container"
 
 docker stop "$container" > /dev/null
